version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - GATSBY_ACTIVE_ENV=${PipelineName} npm run build
artifacts:
  files: 
    - '**/*'
  base-directory: public