version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build -- --pipeline ${PipelineName}
artifacts:
  files: 
    - '**/*'
  base-directory: dist